

# 1. H2 데이터베이스 연결 설정
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. H2 콘솔 활성화 (브라우저에서 DB 확인용)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 실행되는 SQL 쿼리를 콘솔에 출력
spring.jpa.show-sql=true
# 출력되는 SQL을 보기 좋게 포맷팅
spring.jpa.properties.hibernate.format_sql=true

# SQL 스크립트 실행 시점을 Hibernate 초기화 이후로 늦춤 (가장 중요!)
spring.jpa.defer-datasource-initialization=true

# JWT Secret Key (예시 문자열입니다. 실제로는 더 복잡하게 만드세요)
jwt.secret.key=${JWT_SECRET_KEY:}



#ai api key
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash