spring.application.name=delivery

# 1. PostgreSQL 데이터베이스 연결 설정(환경 변수 권장)
spring.datasource.url=jdbc:postgresql://localhost:5432/delivery_db
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:}

# 2. JPA/Hibernate 설정
# 서버를 켤 때마다 테이블을 새로 생성 (엔티티 수정이 잦은 개발 단계에 적합)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 실행되는 SQL 쿼리를 콘솔에 출력
spring.jpa.show-sql=true
# 출력되는 SQL을 보기 좋게 포맷팅
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret Key (예시 문자열입니다. 실제로는 더 복잡하게 만드세요)
jwt.secret.key=${JWT_SECRET_KEY:}

#ai api key
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

